// PptxGenJS script — run with:
// node build_deck.js <path_to_.b64tmp_folder> <output.pptx>
//
// Example (from project root):
//   node slides/build_deck.js .b64tmp slides/ML_Week7_Salary_Prediction.pptx
//
// The b64tmp folder must contain the following base64 files
// (already generated by the notebooks):
//   R2_Modelscomparisons.b64
//   Predictions_Modelscomparison.b64
//   Optuna_optHistory_RFModel.b64
//   HyperparameterImportance_RF.b64
//   boxplot_company_region.b64
//
// Install once: npm install -g pptxgenjs

const pptxgen = require("pptxgenjs");
const fs = require("fs");
const path = require("path");

const B64_DIR = process.argv[2];
const OUT     = process.argv[3];

function fig(name) {
  const b64path = path.join(B64_DIR, name + ".b64");
  if (fs.existsSync(b64path)) {
    return "image/png;base64," + fs.readFileSync(b64path, "utf8").trim();
  }
  return null;
}

const C = {
  dark    : "0F172A",
  navy    : "1E3A5F",
  teal    : "0891B2",
  tealLt  : "CFFAFE",
  white   : "FFFFFF",
  offWhite: "F8FAFC",
  slate   : "475569",
  slateXL : "64748B",
  muted   : "94A3B8",
  placeholder: "CBD5E1",
};

const sh = () => ({ type: "outer", color: "000000", blur: 8, offset: 3, angle: 45, opacity: 0.10 });

let pres = new pptxgen();
pres.layout  = "LAYOUT_16x9";
pres.author  = "Diana Yule & Bibian";
pres.title   = "AI/ML/Data Salary Prediction — ML Week 7";

function titleBar(slide, text, sub) {
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 10, h: 1.15, fill: { color: C.navy } });
  slide.addText(text, { x: 0.45, y: 0.18, w: 9.1, h: 0.72, fontSize: 22, bold: true, color: C.white, fontFace: "Calibri", valign: "middle", margin: 0 });
  if (sub) slide.addText(sub, { x: 0.45, y: 0.82, w: 9.1, h: 0.32, fontSize: 11, color: C.tealLt, fontFace: "Calibri", valign: "middle", margin: 0 });
}
function slideNum(slide, n) {
  slide.addText(`${n}`, { x: 9.5, y: 5.35, w: 0.4, h: 0.2, fontSize: 9, color: C.muted, fontFace: "Calibri", align: "right" });
}
function card(slide, x, y, w, h, fillColor) {
  slide.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, fill: { color: fillColor || C.white }, rectRadius: 0.08, shadow: sh() });
}
function statCallout(slide, value, label, x, y, w) {
  card(slide, x, y, w, 1.3, C.white);
  slide.addText(value, { x: x + 0.1, y: y + 0.08, w: w - 0.2, h: 0.7, fontSize: 36, bold: true, color: C.navy, fontFace: "Cambria", align: "center", valign: "middle", margin: 0 });
  slide.addText(label, { x: x + 0.1, y: y + 0.8, w: w - 0.2, h: 0.42, fontSize: 10, color: C.slate, fontFace: "Calibri", align: "center", valign: "middle", margin: 0 });
}
function bulletBox(slide, items, x, y, w, h) {
  slide.addText(items.map((t, i) => ({ text: t, options: { bullet: true, breakLine: i < items.length - 1 } })), { x, y, w, h, fontSize: 13, color: C.dark, fontFace: "Calibri", valign: "top" });
}
function placeholderCard(slide, x, y, w, h, label) {
  slide.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, fill: { color: C.placeholder }, rectRadius: 0.08 });
  slide.addText(`⏳ ${label}`, { x: x + 0.1, y, w: w - 0.2, h, fontSize: 12, italic: true, color: C.slateXL, fontFace: "Calibri", align: "center", valign: "middle", margin: 0 });
}

// ── SLIDE 1 Title ──────────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.dark };
  s.addShape(pres.shapes.OVAL, { x: 7.8, y: -1.0, w: 4.5, h: 4.5, fill: { color: C.teal, transparency: 82 } });
  s.addShape(pres.shapes.OVAL, { x: -1.2, y: 3.5, w: 3.5, h: 3.5, fill: { color: C.navy, transparency: 50 } });
  s.addText("AI / ML / Data\nSalary Prediction", { x: 0.7, y: 0.85, w: 7.5, h: 2.4, fontSize: 44, bold: true, color: C.white, fontFace: "Cambria", valign: "middle" });
  s.addText("Global AI/ML/Data Roles · Supervised Regression · Random Forest + Optuna", { x: 0.7, y: 3.3, w: 7.8, h: 0.55, fontSize: 14, color: C.tealLt, fontFace: "Calibri" });
  s.addText("Diana Yule · Bibian", { x: 0.7, y: 4.05, w: 5, h: 0.4, fontSize: 13, color: C.muted, fontFace: "Calibri" });
  s.addText("Ironhack Data Analytics Bootcamp — Week 7", { x: 0.7, y: 4.48, w: 7, h: 0.35, fontSize: 11, color: C.slateXL, fontFace: "Calibri" });
  s.addNotes("Welcome! Introduce yourselves. State the goal: predict USD salaries for global AI/ML/Data roles using supervised ML.");
}

// ── SLIDE 2 Project Overview ───────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Project Overview");
  slideNum(s, 2);
  const cols = [
    { x: 0.35, icon: "🎯", head: "Goal", body: "Predict salary_in_usd for global AI / ML / Data roles using supervised regression models." },
    { x: 3.55, icon: "🗂️", head: "Data", body: "aijobs.net · ~34k rows · CC0 licence\nDirect CSV download — no scraping required." },
    { x: 6.75, icon: "🤝", head: "Team Split", body: "Diana → company-side features\n(job title, company size, region, year)\n\nBibian → experience-side features\n(experience level, employment type…)" },
  ];
  cols.forEach(({ x, icon, head, body }) => {
    card(s, x, 1.35, 3.0, 3.95, C.white);
    s.addText(icon, { x: x + 0.1, y: 1.45, w: 2.8, h: 0.6, fontSize: 28, align: "center", valign: "middle", margin: 0 });
    s.addText(head, { x: x + 0.1, y: 2.1, w: 2.8, h: 0.42, fontSize: 15, bold: true, color: C.navy, fontFace: "Cambria", align: "center", margin: 0 });
    s.addText(body, { x: x + 0.18, y: 2.58, w: 2.64, h: 2.5, fontSize: 12, color: C.dark, fontFace: "Calibri", valign: "top" });
  });
  s.addNotes("Both halves use the same algorithm (Random Forest + Optuna) and dataset — results are directly comparable once Bibian is done.");
}

// ── SLIDE 3 Data Preparation ───────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Data Selection & Preparation");
  slideNum(s, 3);
  statCallout(s, "~34k",   "rows in raw dataset",        0.35, 1.35, 2.1);
  statCallout(s, "29,562", "rows after deduplication",   0.35, 2.8,  2.1);
  statCallout(s, "80 / 20","train / test split",         0.35, 4.25, 2.1);
  card(s, 2.7, 1.35, 6.95, 4.0, C.white);
  const steps = [
    ["1. Source",       "aijobs.net — direct CSV download (CC0 licence). No scraping needed."],
    ["2. Drop leakage", "Removed raw local-currency salary column — would trivially leak the target."],
    ["3. Nulls / types","No nulls; all columns in correct dtype after load."],
    ["4. Outlier check","Target (salary_in_usd) heavily right-skewed; kept all rows — no hard cap applied."],
    ["5. Split",        "Stratified 80/20 split on work_year to preserve year distribution."],
  ];
  steps.forEach(([bold, text], i) => {
    s.addText([{ text: bold + " — ", options: { bold: true, color: C.navy } }, { text, options: { color: C.dark } }], { x: 2.95, y: 1.55 + i * 0.70, w: 6.5, h: 0.62, fontSize: 12, fontFace: "Calibri", valign: "top" });
  });
  s.addNotes("Raw dataset from aijobs.net (CC0). Key preprocessing: remove raw salary columns (leakage risk), stratified split.");
}

// ── SLIDE 4 Feature Engineering ────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Feature Engineering & Selection", "Diana's company-side feature set");
  slideNum(s, 4);
  card(s, 0.35, 1.35, 4.5, 4.0, C.white);
  s.addText("🔧 Features Engineered", { x: 0.55, y: 1.42, w: 4.1, h: 0.4, fontSize: 14, bold: true, color: C.navy, fontFace: "Cambria", margin: 0 });
  bulletBox(s, [
    "job_title → rare titles (<150 occurrences) grouped into 'Other'",
    "company_region → 198 country codes → 7 geographic regions",
    "residence_region → same mapping for employee residence",
    "companyloc_residence → boolean flag: HQ country = residence country",
    "work_year → kept as numeric (trend predictor)",
    "company_size → ordinal S/M/L kept as-is",
  ], 0.55, 1.9, 4.2, 3.3);
  card(s, 5.05, 1.35, 4.6, 4.0, C.white);
  s.addText("📊 Feature Selection — ANOVA (η²)", { x: 5.25, y: 1.42, w: 4.2, h: 0.4, fontSize: 14, bold: true, color: C.navy, fontFace: "Cambria", margin: 0 });
  s.addTable([
    [{ text: "Feature", options: { bold: true } }, { text: "η²", options: { bold: true } }, { text: "Kept?", options: { bold: true } }],
    ["job_title (grouped)", "0.063", "✅"],
    ["company_region",      "0.047", "✅"],
    ["company_size",        "0.031", "✅"],
    ["work_year",           "0.018", "✅"],
  ], { x: 5.2, y: 1.92, w: 4.3, h: 1.8, colW: [2.0, 0.9, 0.9], fontFace: "Calibri", fontSize: 12, border: { pt: 0.5, color: "E2E8F0" }, fill: { color: C.white } });
  s.addText("Note: p-values were NOT used as the selection criterion — at ~34k rows, virtually every feature returns p < 0.05. Effect size (η²) is the correct metric for large datasets.", { x: 5.2, y: 3.82, w: 4.3, h: 1.38, fontSize: 10, italic: true, color: C.slateXL, fontFace: "Calibri", valign: "top" });
  s.addNotes("eta-squared = variance explained by the feature. Used because p-values are unreliable at n~34k.");
}

// ── SLIDE 5 Boxplot ─────────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Salary Distribution by Company Region");
  slideNum(s, 5);
  const imgData = fig("boxplot_company_region");
  if (imgData) s.addImage({ data: imgData, x: 0.5, y: 1.25, w: 9.0, h: 4.1, sizing: { type: "contain", w: 9.0, h: 4.1 } });
  else placeholderCard(s, 0.5, 1.25, 9.0, 4.1, "boxplot_company_region.png");
  s.addNotes("North America dominates salary ranges. Regional grouping reduces 100+ country codes to 7 meaningful clusters.");
}

// ── SLIDE 6 Model Building ──────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Model Building & Evaluation (Diana's feature set)");
  slideNum(s, 6);
  const imgData = fig("R2_Modelscomparisons");
  if (imgData) s.addImage({ data: imgData, x: 0.35, y: 1.28, w: 5.8, h: 3.55, sizing: { type: "contain", w: 5.8, h: 3.55 } });
  else placeholderCard(s, 0.35, 1.28, 5.8, 3.55, "R2_Modelscomparisons.png");
  card(s, 6.35, 1.28, 3.3, 3.55, C.white);
  s.addText("Key Findings", { x: 6.55, y: 1.35, w: 2.9, h: 0.38, fontSize: 14, bold: true, color: C.navy, fontFace: "Cambria", margin: 0 });
  bulletBox(s, [
    "All 4 model families converge: R² ≈ 0.20–0.25",
    "KNN, LinReg, RF, Bagging-RF all reach same ceiling",
    "Structural ceiling — not a tuning problem",
    "Next lever: experience_level (Bibian's features)"
  ], 6.55, 1.8, 2.95, 2.8);
  s.addText("Single test-split R² shown. CV mean ≈ 0.217 (RF baseline). Metric: R² (coefficient of determination).", { x: 0.35, y: 4.9, w: 9.3, h: 0.35, fontSize: 9.5, italic: true, color: C.slateXL, fontFace: "Calibri" });
  s.addNotes("All 4 algorithms converge to the same R² ceiling. Diagnostic: feature ceiling, not model/tuning issue.");
}

// ── SLIDE 7 Optuna ──────────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Hyperparameter Tuning — Bayesian Optimisation (Optuna)");
  slideNum(s, 7);
  const histData = fig("Optuna_optHistory_RFModel");
  const impData  = fig("HyperparameterImportance_RF");
  if (histData) s.addImage({ data: histData, x: 0.35, y: 1.28, w: 4.7, h: 3.1, sizing: { type: "contain", w: 4.7, h: 3.1 } });
  else placeholderCard(s, 0.35, 1.28, 4.7, 3.1, "Optuna_optHistory_RFModel.png");
  if (impData) s.addImage({ data: impData, x: 5.2, y: 1.28, w: 4.45, h: 3.1, sizing: { type: "contain", w: 4.45, h: 3.1 } });
  else placeholderCard(s, 5.2, 1.28, 4.45, 3.1, "HyperparameterImportance_RF.png");
  s.addText("Optimisation History (45 trials)", { x: 0.35, y: 4.42, w: 4.7, h: 0.28, fontSize: 10, italic: true, color: C.slateXL, fontFace: "Calibri", align: "center" });
  s.addText("Hyperparameter Importance", { x: 5.2, y: 4.42, w: 4.45, h: 0.28, fontSize: 10, italic: true, color: C.slateXL, fontFace: "Calibri", align: "center" });
  card(s, 0.35, 4.75, 9.3, 0.72, C.tealLt);
  s.addText("Sampler: TPE  ·  45 trials  ·  10-fold CV objective  ·  Tuned: max_depth, min_samples_split, max_leaf_nodes, max_features", { x: 0.55, y: 4.82, w: 9.0, h: 0.58, fontSize: 11, color: C.navy, fontFace: "Calibri", valign: "middle", margin: 0 });
  s.addNotes("Bayesian optimisation with Optuna (TPE sampler). 45 trials, 10-fold CV. Tuned 4 RF params. Negligible gain — confirms feature ceiling.");
}

// ── SLIDE 8 Model Comparison ────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Model Comparison — Baseline vs Optuna-tuned RF");
  slideNum(s, 8);
  const imgData = fig("Predictions_Modelscomparison");
  if (imgData) s.addImage({ data: imgData, x: 0.35, y: 1.28, w: 5.8, h: 3.55, sizing: { type: "contain", w: 5.8, h: 3.55 } });
  else placeholderCard(s, 0.35, 1.28, 5.8, 3.55, "Predictions_Modelscomparison.png");
  card(s, 6.35, 1.28, 3.3, 3.55, C.white);
  s.addText("CV Mean R² Results", { x: 6.55, y: 1.35, w: 2.9, h: 0.38, fontSize: 14, bold: true, color: C.navy, fontFace: "Cambria", margin: 0 });
  s.addTable([
    [{ text: "Model", options: { bold: true, fill: { color: C.navy }, color: C.white } }, { text: "CV R²", options: { bold: true, fill: { color: C.navy }, color: C.white } }],
    ["RF Baseline", "0.217"],
    ["RF + Optuna", "0.220"],
    ["Linear Reg",  "0.162"],
    ["KNN",         "0.198"],
  ], { x: 6.45, y: 1.82, w: 3.0, h: 1.6, colW: [2.0, 1.0], fontFace: "Calibri", fontSize: 12, border: { pt: 0.5, color: "E2E8F0" } });
  s.addText("Optuna gain is within noise (~0.003 R²). Confirms the problem is feature-ceiling, not tuning.\n\nKey takeaway: a better feature set matters more than better tuning.", { x: 6.45, y: 3.5, w: 3.1, h: 1.2, fontSize: 11, color: C.slate, fontFace: "Calibri", valign: "top" });
  s.addText("CV = 10-fold cross-validation. Both values are cross-validated means — comparable apples-to-apples.", { x: 0.35, y: 4.9, w: 9.3, h: 0.35, fontSize: 9.5, italic: true, color: C.slateXL, fontFace: "Calibri" });
  s.addNotes("CV R² ~0.217 baseline vs ~0.220 tuned. Difference within noise. Feature engineering is the real lever.");
}

// ── SLIDE 9 Key Findings ────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Key Findings & Insights");
  slideNum(s, 9);
  const insights = [
    ["🌍 Geography matters",       "North America & Western Europe command significantly higher salaries. Regional grouping captured this signal better than raw country codes."],
    ["📋 Job title signal",         "After grouping rare titles, job_title becomes the strongest company-side predictor (η² = 0.063). Specialised roles (ML Researcher, AI Lead) command clear premiums."],
    ["📉 Feature ceiling is real",  "All 4 model families converge to R² ≈ 0.20–0.25. This convergence across structurally different algorithms is diagnostic — not a model choice issue."],
    ["🔧 Tuning ≠ cure",            "45 Optuna trials gained only ~0.003 R². When you're at a feature ceiling, tuning delivers diminishing returns."],
    ["🧪 R² reporting discipline",  "Single test-split and CV results reported separately. Mixing them inflates apparent performance by 2–3 pp."],
  ];
  insights.forEach(([head, body], i) => {
    const y = 1.32 + i * 0.83;
    card(s, 0.35, y, 9.3, 0.75, C.white);
    s.addText([{ text: head + "  ", options: { bold: true, color: C.navy } }, { text: body, options: { color: C.dark } }], { x: 0.55, y: y + 0.08, w: 9.0, h: 0.60, fontSize: 12, fontFace: "Calibri", valign: "middle" });
  });
  s.addNotes("Walk through each finding. Emphasise the feature ceiling diagnosis — it sets up Bibian's feature set as the next hypothesis.");
}

// ── SLIDE 10 Real-World Application ────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Real-World Application & Impact");
  slideNum(s, 10);
  const apps = [
    { icon: "💼", head: "Salary Benchmarking", body: "HR teams can use a tuned model to flag underpaid roles or benchmark new hires against market ranges — especially valuable in remote-first AI orgs where geography previously anchored pay." },
    { icon: "🎓", head: "Career Navigation",   body: "Job-seekers can estimate the USD salary premium of a title, region, or company-size choice before accepting an offer — actionable beyond simply 'get more experience'." },
    { icon: "📈", head: "Market Trend Tracking", body: "Year-over-year analysis reveals whether specific roles or regions are converging or diverging in pay. The work_year feature already captures a measurable trend." },
  ];
  apps.forEach(({ icon, head, body }, i) => {
    const x = 0.35 + i * 3.22;
    card(s, x, 1.32, 3.0, 3.95, C.white);
    s.addText(icon, { x: x + 0.1, y: 1.42, w: 2.8, h: 0.55, fontSize: 26, align: "center", valign: "middle", margin: 0 });
    s.addText(head, { x: x + 0.12, y: 2.02, w: 2.76, h: 0.42, fontSize: 13, bold: true, color: C.navy, fontFace: "Cambria", align: "center", margin: 0 });
    s.addText(body, { x: x + 0.18, y: 2.52, w: 2.64, h: 2.6, fontSize: 11.5, color: C.dark, fontFace: "Calibri", valign: "top" });
  });
  s.addNotes("Connect the model to real decisions. R² ~0.22 is directionally useful for benchmarking even if not precise for individual predictions.");
}

// ── SLIDE 11 Challenges ─────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Challenges & Learnings");
  slideNum(s, 11);
  const items = [
    ["⚠️ KNN Classifier → Regressor",    "Initially used KNeighborsClassifier on a continuous target. Caught early — always sanity-check estimator type against the task."],
    ["⚖️ StandardScaler on OHE dummies", "Scaling binary (0/1) columns distorts KNN distance. Identified as a known limitation; documented in README."],
    ["📊 p-value trap at n~34k",           "p-values are meaningless at large n — everything is 'significant'. Switched to η² (effect size) for feature selection."],
    ["🔄 Feature engineering before split","Must happen before train/test split to prevent leakage and KeyErrors on unseen test categories."],
    ["📋 R² reporting hygiene",             "Mixing single-split and CV R² overstates performance. Report both explicitly and never compare across methods."],
    ["🔬 Convergence = diagnosis",          "Four structurally different algorithms at the same R² is informative — it's a signal about the feature space, not a failure."],
  ];
  items.forEach(([head, body], i) => {
    const col = i < 3 ? 0 : 1;
    const row = i < 3 ? i : i - 3;
    const x = col === 0 ? 0.35 : 5.12;
    const y = 1.32 + row * 1.37;
    card(s, x, y, 4.6, 1.28, C.white);
    s.addText(head, { x: x + 0.18, y: y + 0.1, w: 4.2, h: 0.35, fontSize: 12, bold: true, color: C.navy, fontFace: "Cambria", valign: "middle", margin: 0 });
    s.addText(body, { x: x + 0.18, y: y + 0.48, w: 4.2, h: 0.72, fontSize: 10.5, color: C.dark, fontFace: "Calibri", valign: "top" });
  });
  s.addNotes("Be candid — showing you understand the mistakes is as valuable as the results.");
}

// ── SLIDE 12 Future Work ────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Future Work & Improvements");
  slideNum(s, 12);
  card(s, 0.35, 1.32, 4.5, 3.95, C.white);
  s.addText("✅ Diana's Half — Done", { x: 0.55, y: 1.38, w: 4.1, h: 0.4, fontSize: 14, bold: true, color: C.navy, fontFace: "Cambria", margin: 0 });
  bulletBox(s, [
    "4 regression model families tested",
    "Optuna Bayesian tuning (45 trials, 10-fold CV)",
    "Feature ceiling diagnosed at R² ≈ 0.22",
    "Pipeline modularised in functions.py",
    "README + figures fully documented",
  ], 0.55, 1.85, 4.2, 3.3);
  card(s, 5.05, 1.32, 4.6, 3.95, C.tealLt);
  s.addText("⏳ Coming — Bibian + Joint Model", { x: 5.25, y: 1.38, w: 4.2, h: 0.4, fontSize: 14, bold: true, color: C.navy, fontFace: "Cambria", margin: 0 });
  bulletBox(s, [
    "Bibian: experience-side features\n(experience_level, employment_type, …)",
    "Same RF + Optuna pipeline — directly comparable",
    "Head-to-head CV R² comparison:\n  company features vs experience features",
    "Combine both feature sets → does a joint model beat either alone?",
    "Final model selection for the capstone write-up",
  ], 5.25, 1.85, 4.25, 3.3);
  s.addNotes("Present as: this is what we locked in; here is what Bibian still needs to complete the picture.");
}

// ── SLIDE 13 Joint Comparison PLACEHOLDER ──────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.offWhite };
  titleBar(s, "Joint Model Comparison", "⏳ Placeholder — insert Bibian's results + combined model chart here");
  slideNum(s, 13);
  placeholderCard(s, 0.35, 1.28, 4.7, 3.85, "Diana R² vs Bibian R² — bar chart");
  placeholderCard(s, 5.25, 1.28, 4.4, 3.85, "Combined feature set R² — comparison");
  s.addText("Replace with: (1) bar chart comparing CV R² for Diana's features, Bibian's features, and the combined model. (2) Error bars from 10-fold CV. (3) Key takeaway.", { x: 0.35, y: 5.15, w: 9.3, h: 0.42, fontSize: 10, italic: true, color: C.slateXL, fontFace: "Calibri", align: "center" });
  s.addNotes("PLACEHOLDER: replace once Bibian completes her RF + Optuna run.");
}

// ── SLIDE 14 Closing ────────────────────────────────────────────────────────
{
  let s = pres.addSlide();
  s.background = { color: C.dark };
  s.addShape(pres.shapes.OVAL, { x: 7.3, y: -1.2, w: 5.0, h: 5.0, fill: { color: C.teal, transparency: 85 } });
  s.addShape(pres.shapes.OVAL, { x: -1.5, y: 3.8, w: 4.0, h: 4.0, fill: { color: C.navy, transparency: 55 } });
  s.addText("Thank You", { x: 0.7, y: 1.0, w: 7.0, h: 1.4, fontSize: 52, bold: true, color: C.white, fontFace: "Cambria", valign: "middle" });
  s.addText("Questions?", { x: 0.7, y: 2.5, w: 5.0, h: 0.65, fontSize: 24, color: C.tealLt, fontFace: "Calibri", italic: true });
  s.addText([{ text: "Dataset: ", options: { bold: true, color: C.muted } }, { text: "aijobs.net/salaries/download/ (CC0)  ", options: { color: C.slateXL } }, { text: "  |  ", options: { color: C.muted } }, { text: "Diana Yule · Bibian", options: { bold: true, color: C.muted } }], { x: 0.7, y: 3.4, w: 8.5, h: 0.5, fontSize: 12, fontFace: "Calibri" });
  s.addText("Ironhack Data Analytics Bootcamp · Week 7 · June 2026", { x: 0.7, y: 4.0, w: 8.0, h: 0.35, fontSize: 10.5, color: C.slateXL, fontFace: "Calibri" });
  s.addNotes("Close with confidence. Mention Bibian's work is still running and you'll have a joint comparison for the capstone.");
}

pres.writeFile({ fileName: OUT })
  .then(() => console.log("✅  Written: " + OUT))
  .catch(e => { console.error("❌  Error:", e); process.exit(1); });
